"""empty message

Revision ID: 1931f8b30463
Revises: 4b27ad951847
Create Date: 2025-03-05 16:20:46.088110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1931f8b30463'
down_revision = '4b27ad951847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_favourite_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('character_favourites_user_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['character_favourite_user_id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['character_favourite_user_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('character_favourites_user_id_key', ['user_id'])
        batch_op.drop_column('character_favourite_user_id')

    # ### end Alembic commands ###
