"""empty message

Revision ID: 899fb293af31
Revises: d368f04bb8b1
Create Date: 2025-03-05 16:08:47.289691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899fb293af31'
down_revision = 'd368f04bb8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=120), nullable=True),
    sa.Column('user_coment_id', sa.Integer(), nullable=False),
    sa.Column('user_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_coment_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_coment_id'),
    sa.UniqueConstraint('user_post_id')
    )
    op.drop_table('comments')
    with op.batch_alter_table('planet_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_favourite_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('planet_favourites_user_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['planet_favourite_user_id'])
        batch_op.create_foreign_key(None, 'users', ['planet_favourite_user_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planet_favourites_user_id_key', ['user_id'])
        batch_op.drop_column('planet_favourite_user_id')

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_comment_id'], ['users.id'], name='comments_user_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_post_id'], ['posts.id'], name='comments_user_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    sa.UniqueConstraint('user_comment_id', name='comments_user_comment_id_key'),
    sa.UniqueConstraint('user_post_id', name='comments_user_post_id_key')
    )
    op.drop_table('coments')
    # ### end Alembic commands ###
