"""empty message

Revision ID: 986c69e20351
Revises: a3740ec69a18
Create Date: 2025-03-05 15:41:42.088430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986c69e20351'
down_revision = 'a3740ec69a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
