"""empty message

Revision ID: ab5f539f4282
Revises: ef0879b72af6
Create Date: 2025-03-11 13:32:44.318660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5f539f4282'
down_revision = 'ef0879b72af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favourites', schema=None) as batch_op:
        batch_op.alter_column('character_favourite_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('character_favourites_character_favourite_user_id_key', type_='unique')
        batch_op.drop_constraint('character_favourites_character_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favourites', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_favourites_character_id_key', ['character_id'])
        batch_op.create_unique_constraint('character_favourites_character_favourite_user_id_key', ['character_favourite_user_id'])
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('character_favourite_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
