"""empty message

Revision ID: d368f04bb8b1
Revises: ddf2f92ab9aa
Create Date: 2025-03-05 15:57:31.970287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd368f04bb8b1'
down_revision = 'ddf2f92ab9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_comment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comments_post_id_key', type_='unique')
        batch_op.drop_constraint('comments_user_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_comment_id'])
        batch_op.create_unique_constraint(None, ['user_post_id'])
        batch_op.create_foreign_key(None, 'posts', ['user_post_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_comment_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('comments_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('comments_post_id_key', ['post_id'])
        batch_op.drop_column('user_post_id')
        batch_op.drop_column('user_comment_id')

    # ### end Alembic commands ###
