"""empty message

Revision ID: ef0879b72af6
Revises: f26e5615e887
Create Date: 2025-03-11 13:10:46.412117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0879b72af6'
down_revision = 'f26e5615e887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet_favourites', schema=None) as batch_op:
        batch_op.alter_column('planet_favourite_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('planet_favourites_planet_favourite_user_id_key', type_='unique')
        batch_op.drop_constraint('planet_favourites_planet_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet_favourites', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_favourites_planet_id_key', ['planet_id'])
        batch_op.create_unique_constraint('planet_favourites_planet_favourite_user_id_key', ['planet_favourite_user_id'])
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_favourite_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
